travis:
  secure:
    BINSTAR_TOKEN: nHgW01VLtqPnUrfnbJpk7gMylN9n6r11XqdknERk8jJHLMrImupjaEudETFLiyFUCWIa18EI9AEcbraHwcvqdeQAZ7NsR0PeMdHtvZdWRuNtlLi9SMDkjak0YP6qR9ytdA23R+RpKDU5ymWBit5BZb0gkysH1LrKB2ERaofo/CGFiAO1Zh5yeH5nfVbAA4pojYbsWG97aUTyrdcNt7Ja8sxlIWJ1s0Tq5/7EnDKgYcUHIsii7+uPumNkFURSbNzJQZI9PDstpwvFgEQe6j0ONm9smaxRxYsA9Ep/RCGHGBCgTf4y+kogyla2/SV7nowmd96/7py5a+6sApxd3oziktmeNJ1XsRezeDLpt06PG+HdNx3MstPgHlB75H04O7nPK4O1s58CIj4hwBYCABOEm8e5PgFhIBZWNUz/S/uUCyE1ysOFxT3TKrFDmq50ewNIzsfUZkVRx2vYkIqrR1EApK3Avq1ta/UxhKZRkT/bvyqbs+M/U8F7eGSQG9ZRfzxTcol6uJ+zCcgvzS+PkDRqhQ990K0vZhu2lyNvhsEwnKzoegaTSV7ai2SfoBaslGBnsKyf5jpc3rkjHfW5zRdN0gBkgMJXVbHsWagxtE7GVTgf6hgHmF12PcVthyptQtEM7bQlPesgRdySX0vd6ELwoeE3d897M+EC+g7HN2R8fPI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
