travis:
  secure:
    BINSTAR_TOKEN: OR92lc2rDDIGP7uBVPPi1GSb0ESH//eMX3QicV6XNksWvvVT77CkugU8TdVUZSX78pzIBG/N/OEv7c8tgglj7YMSEiIGBj0JHGENm87+dZjY2KkKY1QdmACiWRW3YemtoUkEjkLX/uCphxhqmwB52MDUEa2J7SHW3BW36UVL/SOnIbgDmgg7p74ghBpCHpZIaOGlLP3kBWo7yeJqXyIYBxxEZUAGgovbjRlccChvQWRiC3BxOiSafUjY4Ca/X6ZlN26JfPNLNN9QgEBg6BUGcA08swMUzs8JCq96nVb3/uO+HG9qx/9s+fvOCi6xAKuFjtV5zTzpvXH3yeQ/2XZislOSaaO2drZqIJLRW6LNkgVDHAeEQt+Ne2ovnpMIbffBlYCkojK6DDt0dkypKKNRFP20NCNPTVoDvJ5BGx/L2tgVGpQ8ue2d3Ns22iY99llwdUQ3Vl3o1dWEDg+ez+r+6PALKcpXVD+mmxP4ot0DhejE/5lioKHdLtxcMTerRd6z05d5IzmWU8xOkFQF0nY87Z2StuWJL5/3F8DZBxW5CUVr3XYq/M19R/qRwtH1Am7sknVKOVwyQcu0OHlqQBd+0jeXu3VfZUAqLb9Ud3Vh1zXec5G9jQ9q61SFR6lIY+zaDgWnRD7eWh0eG5lP26XM0B3hSXEoqf9u96Wlv9xdzkw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
